### ISSUE TITLE
Excellent! What do I have to do to get it running on `vimeo/psalm`?

### ISSUE THREAD

**Issue by weirdan** [weirdan/psalm-github-bot#1]
Excellent! What do I have to do to get it running on `vimeo/psalm`?

Also could it warn if no `psalm.dev` link is given on the first issue comment, and `psalm.dev` is not mentioned (I don't want it complain if someone says "I wasn't able to reproduce on psalm.dev")

_Originally posted by @muglug in https://github.com/psalm/psalm.dev/pull/15#issuecomment-563039235_

**Comment by weirdan** [comment]
@muglug I need to figure out the way to deploy it to glitch.com and then it can be opened to general public - Github only allows me to limit the app access to the organizations I'm a member of, so it must be public for you to use it.

**Comment by muglug** [comment]
Behold an avatar

![FC7E05F5-9656-4AFF-A6FC-26E5B714D082](https://user-images.githubusercontent.com/2292638/70405348-e27c1800-1a0a-11ea-8410-82b03ed752cb.jpeg)

**Comment by muglug** [comment]
Slightly better at size:

![FAF4B1A2-64F8-4964-A58E-D2A31940BC87](https://user-images.githubusercontent.com/2292638/70410382-e44ed700-1a1c-11ea-9c66-5449f0031930.png)

**Comment by weirdan** [comment]
@muglug the app went public and you should be able to install it now from here https://github.com/apps/psalm-github-bot

**Comment by muglug** [comment]
Thanks!
