### ISSUE TITLE
suggestion: accessible twitter image bot

### ISSUE THREAD

**Issue by SignpostMarv** [weirdan/psalm-github-bot#23]
if someone mentions `@psalmphp` on twitter with a link to psalm.dev in the message body, the github bot's source & result retrieval could be used to generate syntax-highlighted source code snippets, apply appropriate image descriptions, then reply to the tweet, so code could be checked at a glance without needing to leave twitter.

**Comment by weirdan** [comment]
Would have to be implemented as a separate project I think. I don't see much overlap between twitter and github bot, apart from fetching the data from psalm.dev, which is just a couple of lines (see https://github.com/weirdan/psalm-github-bot/blob/master/src/SnippetResolver/index.ts) And probot framework I'm using here does only provide github integration.
