### ISSUE TITLE
Commit fixtures/issues.opened.json?

### ISSUE THREAD

**Issue by LeSuisse** [weirdan/psalm-github-bot#9]
Test suite fails because the fixture `issues.opened.json` is missing in the repo. Is it expected?

https://github.com/weirdan/psalm-github-bot/blob/eeebaa3894f56997c0c4cbe78d53956fe7af14f3/test/index.test.ts#L9

**Comment by weirdan** [comment]
I guess I just have to drop that test, as I haven't figured out a way to properly mock github webhooks yet.
